language: node_js
node_js:
- "stable"
cache:
directories:
- node_modules
script:
- npm run build
deploy:
provider: surge
project: ./build/
domain: https://supply-ai-assignment.surge.sh
skip_cleanup: true
on:
branch: master